import { Product } from "@mall/types"; // 또는 '@/types/product'

export const FEATURED_PRODUCTS: Product[] = [
  {
    productId: "prod-001",
    productName: "시그니처 미니멀 텀블러 500ml",
    mainImageUrl: "https://via.placeholder.com/400x400?text=Tumbler",
    subImageUrls: [],
    description: "매일 함께하는 고품질 스테인리스 텀블러",
    status: "DISPLAY",
    sortOrder: 1,
    price: {
      basePrice: 40000,
      discountedPrice: 35000,
      discountType: "FIXED_AMOUNT",
      discountValue: 5000,
    },
    options: [
      {
        optionId: "opt-1",
        optionName: "색상",
        optionValue: "Matt Black",
        surcharge: 0,
        skuId: "sku-001",
      },
    ],
    categoryIds: ["cat-1"],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    productId: "prod-002",
    productName: "데일리 에코 캔버스 백",
    mainImageUrl: "https://via.placeholder.com/400x400?text=Canvas+Bag",
    subImageUrls: [],
    description: "내구성이 뛰어난 오가닉 캔버스 소재의 토트백",
    status: "DISPLAY",
    sortOrder: 2,
    price: {
      basePrice: 42000,
      discountedPrice: 42000,
    },
    options: [],
    categoryIds: ["cat-2"],
    createdAt: "2026-01-02T00:00:00Z",
    updatedAt: "2026-01-02T00:00:00Z",
  },
  {
    productId: "prod-003",
    productName: "아로마 우드 디퓨저 100ml",
    mainImageUrl: "https://via.placeholder.com/400x400?text=Diffuser",
    subImageUrls: [],
    description: "은은한 우디 향이 공간을 채우는 디퓨저",
    status: "DISPLAY",
    sortOrder: 3,
    price: {
      basePrice: 35000,
      discountedPrice: 28000,
      discountType: "PERCENTAGE",
      discountValue: 20,
    },
    options: [],
    categoryIds: ["cat-3"],
    createdAt: "2026-01-03T00:00:00Z",
    updatedAt: "2026-01-03T00:00:00Z",
  },
  {
    productId: "prod-004",
    productName: "오가닉 코튼 머그잔 세트",
    mainImageUrl: "https://via.placeholder.com/400x400?text=Mug+Set",
    subImageUrls: [],
    description: "따뜻한 질감의 세라믹 머그잔 2개 세트",
    status: "DISPLAY",
    sortOrder: 4,
    price: {
      basePrice: 31000,
      discountedPrice: 31000,
    },
    options: [],
    categoryIds: ["cat-1"],
    createdAt: "2026-01-04T00:00:00Z",
    updatedAt: "2026-01-04T00:00:00Z",
  },
];