"use client";
import { useCallback, useEffect, useState } from "react";
import type { Product, ProductPost } from "@mall/types";
import { useImageApi } from "../images/useImageApi";
import type { PendingImage } from "@/component/products/post/editor/useEditSection";

export function useProductPostEdit(productPostId: string) {
    const [draftPost, setDraftPost] = useState<ProductPost | null>(null); const [draftProducts, setDraftProducts] = useState<Product[]>([]);
    const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
    const [thumbnailFile, setThumbnailFile] = useState<File | null>(null); const [pendingImages, setPendingImages] = useState<PendingImage[]>([]); const { uploadImage, uploadContentImages } = useImageApi();
    const fetchProductPost = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/admin/product-posts/${productPostId}`); const result = await response.json(); if (!response.ok) throw new Error(result?.message ?? "상품 게시물을 불러오지 못했습니다."); setDraftPost(result.data as ProductPost); setDraftProducts(Array.isArray(result.products) ? result.products as Product[] : []); return result.data as ProductPost; } catch (cause) { setError(cause instanceof Error ? cause.message : "상품 게시물을 불러오지 못했습니다."); return null; } finally { setLoading(false); } }, [productPostId]);
    useEffect(() => { if (productPostId) void fetchProductPost(); }, [productPostId, fetchProductPost]);
    const updatePost = useCallback((post: ProductPost) => setDraftPost(post), []); const addProduct = useCallback((product: Product) => setDraftProducts((items) => [...items, product]), []); const updateProduct = useCallback((product: Product) => setDraftProducts((items) => items.map((item) => item.id === product.id ? product : item)), []); const removeProduct = useCallback((id: string) => setDraftProducts((items) => items.filter((item) => item.id !== id)), []); const moveProduct = useCallback((from: number, to: number) => setDraftProducts((items) => { const next = [...items]; const [item] = next.splice(from, 1); if (item) next.splice(to, 0, item); return next; }), []);
    const saveProductPost = useCallback(async () => { if (!draftPost) return; setSaving(true); setError(null); try { let thumbnailUrl = draftPost.thumbnailUrl; if (thumbnailFile) thumbnailUrl = (await uploadImage(thumbnailFile)).imageUrl; const content = await uploadContentImages(draftPost.content, pendingImages); const response = await fetch(`/api/admin/product-posts/${productPostId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...draftPost, content, thumbnailUrl, productIds: draftProducts.map((item) => item.id) }) }); if (!response.ok) throw new Error("상품 게시물 저장에 실패했습니다."); } catch (cause) { setError(cause instanceof Error ? cause.message : "상품 게시물 저장에 실패했습니다."); throw cause; } finally { setSaving(false); } }, [draftPost, draftProducts, pendingImages, productPostId, thumbnailFile, uploadContentImages, uploadImage]);
    const deleteProductPost = useCallback(async () => { const response = await fetch(`/api/admin/product-posts/${productPostId}`, { method: "DELETE" }); if (!response.ok) throw new Error("상품 게시물 삭제에 실패했습니다."); }, [productPostId]);
    return { draftPost, draftProducts, thumbnailFile, setThumbnailFile, pendingImages, setPendingImages, loading, saving, error, fetchProductPost, updatePost, addProduct, updateProduct, removeProduct, moveProduct, saveProductPost, deleteProductPost };
}
